### PR TITLE
Update to the latest version of AsyncTask.

### PR DESCRIPTION
**Pull request by dellis1972**
This includes a `CancelableTask` which people
can also derive from for tasks which need
to support being stopped by the user.

### CODE REVIEW

**Comment by dellis1972** [comment]
@kzu  sorry about the large diff, but it seems we diverged quite a bit from https://github.com/xamarin/xamarin-android/blob/master/src/Xamarin.Android.Build.Tasks/Tasks/AsyncTask.cs

**Comment by kzu** [comment]
Any reason for cancelling the build?
Any chance XA can take a depender on this nuget to avoid divergence in the future? I'm already using this in other projects ;)

**Comment by dellis1972** [comment]
@kzu I cancelled the build since I wasn't sure if it was gonna publish stuff :) The reason for me updating this is I want to move x-a over to using the Nuget and we need these changes.

**Comment by kzu** [comment]
ok, I let the build run and it failed https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2500432. 

Do let it run, nothing will be published to nuget.org (there's a separate RD for that), but you should be able to build and test the produced nuget package from the uploaded artifact or reported status check

**Pull request merged**
